export const JobData = [
  {
    jobTitle: "UX UI Designer",
    companyName: "Great Vibes",
    industry: "Information Technology",
    location: "Chennai, Tamilnadu, India",
    remoteType: "In-office",
    minExperience: "1",
    maxExperience: "2",
    minSalary: "30,000",
    maxSalary: "50,000",
    totalEmployee: "100",
    applyType: "quickApply",
  },
  {
    jobTitle: "Developer",
    companyName: "Great Vibes",
    industry: "Information Technology",
    location: "Chennai, Tamilnadu, India",
    remoteType: "In-office",
    minExperience: "1",
    maxExperience: "2",
    minSalary: "30,000",
    maxSalary: "50,000",
    totalEmployee: "100",
    applyType: "externalApply",
  },
  {
    jobTitle: "Interaction Designer",
    companyName: "Great Vibes",
    industry: "Information Technology",
    location: "Chennai, Tamilnadu, India",
    remoteType: "In-office",
    minExperience: "1",
    maxExperience: "2",
    minSalary: "30,000",
    maxSalary: "50,000",
    totalEmployee: "100",
    applyType: "externalApply",
  },
  {
    jobTitle: "SEO Analyst",
    companyName: "Great Vibes",
    industry: "Information Technology",
    location: "Chennai, Tamilnadu, India",
    remoteType: "In-office",
    minExperience: "1",
    maxExperience: "2",
    minSalary: "30,000",
    maxSalary: "50,000",
    totalEmployee: "100",
    applyType: "quickApply",
  },
];
